name: Checks

on: [pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install
        run: |
          pip install -U poetry
          poetry install
      - name: Lint
        run: |
          poetry run ruff check .
      - name: Audit
        run: |
          poetry run ruff check --unsafe-fixes .
      - name: Test
        run: |
          poetry run pytest
      - name: Build
        run: |
          poetry build
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: main.py
          requirements: pyproject.toml
          upload_exe_with_name: clean-pma
          options: --onefile, --name "Clea PMA",
